#pragma once

// From glfw3.h
#define RS_MOUSE_BUTTON_1      0
#define RS_MOUSE_BUTTON_2      1
#define RS_MOUSE_BUTTON_3      2
#define RS_MOUSE_BUTTON_4      3
#define RS_MOUSE_BUTTON_5      4
#define RS_MOUSE_BUTTON_6      5
#define RS_MOUSE_BUTTON_7      6
#define RS_MOUSE_BUTTON_8      7
#define RS_MOUSE_BUTTON_LAST   RS_MOUSE_BUTTON_8
#define RS_MOUSE_BUTTON_LEFT   RS_MOUSE_BUTTON_1
#define RS_MOUSE_BUTTON_RIGHT  RS_MOUSE_BUTTON_2
#define RS_MOUSE_BUTTON_MIDDLE RS_MOUSE_BUTTON_3